[env]
CARGO_WORKSPACE_ROOT = { value = "", relative = true }
CHRONO_TZ_TIMEZONE_FILTER = "US/Pacific"

[target.aarch64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=neoverse-n1"]

[target.aarch64-apple-darwin]
rustflags = ["-Ctarget-cpu=apple-m1"]

[target.x86_64-pc-windows-msvc]
# FORCE:MULTIPLE is a bit sketchy. v8 and rocksdb both export the same symbol.
# This seems to work around it to build on windows, but it's not ideal.
rustflags = [
    "-Clink-arg=/FORCE:MULTIPLE",
    "-Clink-arg=/STACK:4194304",
    "-Ctarget-feature=+crt-static",
    "-Clink-arg=/DEFAULTLIB:libcmt",
    "-Clink-arg=/DEFAULTLIB:libvcruntime",
    "-Clink-arg=/DEFAULTLIB:libucrt"
]

[target.x86_64-pc-windows-msvc.env]
RUSTFLAGS = "-Ctarget-feature=+crt-static"
ROCKSDB_LIB_DIR = ""
LIBROCKSDB_STATIC = "1"
ROCKSDB_STATIC_LIB = "1"
VCPKG_ALL_STATIC = "1"

[target.'cfg(all())']
rustflags = ["--cfg", "tokio_unstable"]

[net]
git-fetch-with-cli = true
